---------------------------------------Congress---------------------------


CREATE OR REPLACE TABLE congress_omni_l1 AS

WITH base AS (
    SELECT
        CUSTOMER_ID,
        TIER,
        CONGRESS_NAME,
        MODE,
        month(to_date(start_time)) AS MONTH_DATE,
        YEAR(to_date(START_TIME))                AS YEAR_NUM,
        REGISTERED,
        ATTENDED,
        BOOTH_VISIT,
        POST_CONGRESS_FOLLOWUP
    FROM congress_omni
)


SELECT
    'MONTHLY' AS GRANULARITY,
    MONTH_DATE AS PERIOD,
    'ALL' AS SUB_GRANULARITY,
    'ALL' AS SUB_GRANULARITY_VALUE,

    COUNT_IF(REGISTERED = TRUE)            AS TOTAL_REGISTRATIONS,
    COUNT_IF(ATTENDED = TRUE)              AS TOTAL_ATTENDED,
    COUNT_IF(BOOTH_VISIT = TRUE)           AS TOTAL_BOOTH_VISIT,
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE) AS TOTAL_POST_CONGRESS_FOLLOWUP,

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END)            AS HCP_REGISTERED,
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END)              AS HCP_ATTENDED,
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END)           AS HCP_BOOTH_VISIT,
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END) AS HCP_POST_CONGRESS_FOLLOWUP

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'MONTHLY',
    MONTH_DATE,
    'TIER',
    TIER,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'MONTHLY',
    MONTH_DATE,
    'CONGRESS_NAME',
    CONGRESS_NAME,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'MONTHLY',
    MONTH_DATE,
    'MODE',
    MODE,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4



UNION ALL


SELECT
    'YEARLY',
    YEAR_NUM,
    'ALL',
    'ALL',

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'YEARLY',
    YEAR_NUM,
    'TIER',
    TIER,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'YEARLY',
    YEAR_NUM,
    'CONGRESS_NAME',
    CONGRESS_NAME,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL


SELECT
    'YEARLY',
    YEAR_NUM,
    'MODE',
    MODE,

    COUNT_IF(REGISTERED = TRUE),
    COUNT_IF(ATTENDED = TRUE),
    COUNT_IF(BOOTH_VISIT = TRUE),
    COUNT_IF(POST_CONGRESS_FOLLOWUP = TRUE),

    COUNT(DISTINCT CASE WHEN REGISTERED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN ATTENDED = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN BOOTH_VISIT = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN POST_CONGRESS_FOLLOWUP = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4
;