----------Emails--------------

CREATE OR REPLACE TABLE email_omni_l1 AS

WITH base AS (
    SELECT
        CUSTOMER_ID,
        TIER,
        EMAIL_TYPE,
        SUBJECT_CATEGORY,
        month(to_date(email_date)) AS MONTH_DATE,
        YEAR(to_date(EMAIL_DATE))                AS YEAR_NUM,
        DELIVERY_STATUS,
        OPENED_FLAG,
        CLICKED_FLAG,
        REACH_BACK
    FROM email_omni
)



SELECT
    'MONTHLY' AS GRANULARITY,
    MONTH_DATE AS PERIOD,
    'ALL' AS SUB_GRANULARITY,
    'ALL' AS SUB_GRANULARITY_VALUE,

    COUNT_IF(DELIVERY_STATUS = 'Delivered') AS SENT_COUNT,
    COUNT_IF(DELIVERY_STATUS = 'Bounced')   AS BOUNCE_COUNT,
    COUNT_IF(OPENED_FLAG = TRUE)            AS OPEN_COUNT,
    COUNT_IF(CLICKED_FLAG = TRUE)           AS CLICK_COUNT,
    COUNT_IF(REACH_BACK = TRUE)             AS REACH_BACK_COUNT,

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END) AS HCP_REACHED,
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END)            AS HCP_OPENED,
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)           AS HCP_CLICKED

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'MONTHLY',
    MONTH_DATE,
    'TIER',
    TIER,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'MONTHLY',
    MONTH_DATE,
    'EMAIL_TYPE',
    EMAIL_TYPE,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'MONTHLY',
    MONTH_DATE,
    'SUBJECT_CATEGORY',
    SUBJECT_CATEGORY,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4



UNION ALL



SELECT
    'YEARLY',
    YEAR_NUM,
    'ALL',
    'ALL',

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'YEARLY',
    YEAR_NUM,
    'TIER',
    TIER,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'YEARLY',
    YEAR_NUM,
    'EMAIL_TYPE',
    EMAIL_TYPE,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4

UNION ALL



SELECT
    'YEARLY',
    YEAR_NUM,
    'SUBJECT_CATEGORY',
    SUBJECT_CATEGORY,

    COUNT_IF(DELIVERY_STATUS = 'Delivered'),
    COUNT_IF(DELIVERY_STATUS = 'Bounced'),
    COUNT_IF(OPENED_FLAG = TRUE),
    COUNT_IF(CLICKED_FLAG = TRUE),
    COUNT_IF(REACH_BACK = TRUE),

    COUNT(DISTINCT CASE WHEN DELIVERY_STATUS = 'Delivered' THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN OPENED_FLAG = TRUE THEN CUSTOMER_ID END),
    COUNT(DISTINCT CASE WHEN CLICKED_FLAG = TRUE THEN CUSTOMER_ID END)

FROM base
GROUP BY 1,2,3,4
;

